//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITNTMARK.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITNTMARK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [ 완료 데이터 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string @__Complete_Data__ {
            get {
                return ResourceManager.GetString("[ Complete Data ]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ 예정 데이터 ]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string @__Scheme_Data__ {
            get {
                return ResourceManager.GetString("[ Scheme Data ]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   차종과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAR_TYPE {
            get {
                return ResourceManager.GetString("CAR TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서열번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COMMIT {
            get {
                return ResourceManager.GetString("COMMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   날짜과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 최종 수신 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LAST_UPDATE {
            get {
                return ResourceManager.GetString("LAST UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MODEL {
            get {
                return ResourceManager.GetString("MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지역과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string REGION {
            get {
                return ResourceManager.GetString("REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   남은 데이터 수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string REMAIN_COUNT {
            get {
                return ResourceManager.GetString("REMAIN COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 요청과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string REQUEST_DATA {
            get {
                return ResourceManager.GetString("REQUEST DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   결과과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RESULT {
            get {
                return ResourceManager.GetString("RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   운전준비과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STAND_BY {
            get {
                return ResourceManager.GetString("STAND_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   차 대 번 호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VEHICLE_IDENTIFICATION_NUMBER {
            get {
                return ResourceManager.GetString("VEHICLE IDENTIFICATION NUMBER", resourceCulture);
            }
        }
    }
}
